/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.0.1   2018-08-05

The MIT License (MIT)
Copyright (c) 2018 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include "stm32f4xx.h"
#include <stdio.h>
#include <math.h>
#include "myLib.h"
#include "fft.h"
#include "Elaborazioni.h"
#define ARM_MATH_CM4
#include <arm_math.h>
#include <arm_const_structs.h>

/* Private macro */



typedef enum {ATTESA = 0, SWAP, FFT} states_t;

/* Private variables */

float dataBuffer0_X[n_C], dataBuffer0_Y[n_C], dataBuffer0_Z[n_C];
float dataBuffer1_X[n_C], dataBuffer1_Y[n_C], dataBuffer1_Z[n_C];
complex fft_X[n_C/2], fft_Y[n_C/2], fft_Z[n_C/2];
float *workBuf_X, *workBuf_Y, *workBuf_Z;
//Beta e alpha angoli di rotazione. Cosb,sinb,cosa,sina, variabili dove salvare i valori calcolati di cos e sin
float beta, alpha, cosb, sinb, cosa, sina;
extern float *storeBuf_X, *storeBuf_Y, *storeBuf_Z; //Da condividere con la ISR
extern u16 cont; //Da condividere con la ISR

arm_rfft_fast_instance_f32 S;  //Struttura di configurazione di RFFT

float rotMat[3][3];
/* Private function prototypes */
/* Private functions */

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/

states_t statoCorrente = ATTESA;

int main(void)
{

	//Inizializzazione dei puntatori ai buffer
	storeBuf_X = dataBuffer0_X;
	storeBuf_Y = dataBuffer0_Y;
	storeBuf_Z = dataBuffer0_Z;

	workBuf_X = dataBuffer1_X;
	workBuf_Y = dataBuffer1_Y;
	workBuf_Z = dataBuffer1_Z;

	//Inizializzazione FFT
	arm_rfft_fast_init_f32(&S,1024);

	//Contatore di riempimento del buffer azzerato
	cont = 0;

    myUSART2_Init();
	myAccBoard_Init();
	myLED_Init();

  /* Infinite loop */
	while (1)
	{
		switch(statoCorrente){

		case ATTESA:
		{
           if(cont == n_C){
        	   statoCorrente = SWAP;
           }

           break;
		}

		case SWAP:
		{

			//printf("Numero campioni acquisiti: %d\n", cont);
		    float *temp = workBuf_X;
			workBuf_X = storeBuf_X;
			storeBuf_X = temp;

			temp = workBuf_Y;
			workBuf_Y = storeBuf_Y;
			storeBuf_Y = temp;

			temp = workBuf_Z;
			workBuf_Z = storeBuf_Z;
			storeBuf_Z = temp;

			statoCorrente = FFT;
			cont = 0;
			GPIO_ToggleBits(GPIOA,GPIO_Pin_5);
			break;
		}
		case FFT: {

			//Sezione RFFT (FFT reale)
			//Da un segnale reale produce N/2 campioni complessi nel DF
			//Il prototipo della RFFT intende come buffer di uscita un buffer float
			//organizzato alternando prima la parte reale, e poi quella immaginaria
			//Il casting è obbligatorio, ma nella pratica i dati si troveranno in formato comlesso
		//	printf("FFT\r\n");
			arm_rfft_fast_f32(&S,workBuf_X,(float *)fft_X,0);
			arm_rfft_fast_f32(&S,workBuf_Y,(float *)fft_Y,0);
			arm_rfft_fast_f32(&S,workBuf_Z,(float *)fft_Z,0);
		  //  printf("Ho calcolato le FFT. . .\r\n");
		  //  printf("Normalizzo\r\n");
		    for(int i=0;i<n_C/2;i++)
		    {
		    	fft_X[i].re /= n_C;
		    	fft_X[i].im /= n_C;
		    	fft_Y[i].re /= n_C;
		    	fft_Y[i].im /= n_C;
		    	fft_Z[i].re /= n_C;
		    	fft_Z[i].im /= n_C;
		    }

//			printf("Stampo i valori della DC:\r\n");
//			printf("X:%f,Y:%f,Z:%f\r\n",fft_X[0].re,fft_Y[0].re,fft_Z[0].re);
		 //   printf("FFT terminata\r\n");
		    //Fine FFT

		    //Rotazione
		  //  printf("Rotazione\r\n");

		    //Calcolo angolo beta
		    beta = -atan2(fft_X[0].re, fft_Z[0].re);
		    //Salvo cos e sin di beta
		    cosb = cos(beta);
            sinb = sin(beta);

            //Cacolo angolo alpha
            alpha = atan2(fft_Y[0].re, (cosb*fft_Z[0].re)-(sinb*fft_X[0].re));
            //Salvo cos e sin di alpha
            cosa = cos(alpha);
            sina = sin(alpha);

		    //Inizializzo la matrice di rotazione
		    //printf("Matrice\r\n");
		    matriceDiRotazione_Init(rotMat, cosb, sinb, cosa, sina);

		    //Calcolo il prodotto tra i vettori FFT e la matrice
		    //Le destinazioni sono i work_buff, visti stavolta come buffer complex, per risparmiare memoria
		    //visto che i campioni nel DT non servono più
		  //  printf("Prodotto\r\n");

		   /* complex *workBuf_X_cplx = (complex *) workBuf_X;
		    complex *workBuf_Y_cplx = (complex *) workBuf_Y;
		    complex *workBuf_Z_cplx = (complex *) workBuf_Z;
		    for(int i=0;i<n_C/2;i++)
		    {
		    	workBuf_X_cplx[i] = complex_add(complex_multiply_r_c(rotMat[0][0],fft_X[i]),complex_multiply_r_c(rotMat[0][1],fft_Y[i]));
		    	workBuf_X_cplx[i] = complex_add(workBuf_X_cplx[i], complex_multiply_r_c(rotMat[0][2],fft_Z[i]));

		    	workBuf_Y_cplx[i] = complex_add(complex_multiply_r_c(rotMat[1][0],fft_X[i]),complex_multiply_r_c(rotMat[1][1],fft_Y[i]));
		    	workBuf_Y_cplx[i] = complex_add(workBuf_Y_cplx[i], complex_multiply_r_c(rotMat[1][2],fft_Z[i]));

		    	workBuf_Z_cplx[i] = complex_add(complex_multiply_r_c(rotMat[2][0],fft_X[i]),complex_multiply_r_c(rotMat[2][1],fft_Y[i]));
				workBuf_Z_cplx[i] = complex_add(workBuf_Z_cplx[i], complex_multiply_r_c(rotMat[2][2],fft_Z[i]));
		    }

		    printf("X:%f, Y:%f, Z:%f \r\n", workBuf_X_cplx[0].re, workBuf_Y_cplx[0].re, workBuf_Z_cplx[0].re);*/

            //IMPLEMENTAZIONE MIAAA
		    complex *workingBuf_X_cplx = (complex *) workBuf_X;
		    complex *workingBuf_Y_cplx = (complex *) workBuf_Y;
		    complex *workingBuf_Z_cplx = (complex *) workBuf_Z;

		    workingBuf_X_cplx = rotazione_X(rotMat, fft_X, fft_Y, fft_Z, workBuf_X);
		    workingBuf_Y_cplx = rotazione_Y(rotMat, fft_X, fft_Y, fft_Z, workBuf_Y);
		    workingBuf_Z_cplx= rotazione_Z(rotMat, fft_X, fft_Y, fft_Z, workBuf_Z);

		    printf("X:%f, Y:%f, Z:%f\r\n", workingBuf_X_cplx[0].re, workingBuf_Y_cplx[0].re, workingBuf_Z_cplx[0].re);

		   // printf("Fine Rotazione\r\n");
			statoCorrente = ATTESA;
			break;
		}

		}
		
		//myDelay_ms(5000);

  }
}



